### ISSUE TITLE
Link to documentation from Rubygems is wrong

### ISSUE THREAD

**Issue by yb66** [rspec/rspec-its#41]
The link is: https://relishapp.com/palfvin/rspec-its/docs/attribute-of-subject

Not sure where it's supposed to point to.

Regards,
iain

**Comment by JonRowe** [comment]
@palfvin / @myronmarston you two are the owners of the gem, and I can't see anything in the gemspec causing this, can you have a look on rubygems and see whats going on?

P.s apologies for the time taken to check this @yb66

**Comment by myronmarston** [comment]
I have no idea.  I poked around a bit and can't find where that's coming from either.  @palfvin probably knows since it's a link to his relish account.

**Comment by palfvin** [comment]
@JonRowe @myronmarston I'm sorry, but I have no recollection of this. I checked my relish account and there is no record of me publishing anything and no history of any documentation entry in the .gemspec file prior to October of last year, when a link to rubydocs was added by someone else.

Could the rubygems documentation link be left over from some earlier rubygems publication that didn't get removed when it later pushed without that link?

In any event, while I assume bumping the version number and republishing at this point would fix it, I frankly haven't done anything with Ruby for years, let alone followed what's going on with rspec or maintained this gem. I feel like I should formally extract myself rather than leave any impression of stewardship.

**Comment by JonRowe** [comment]
If one of you wants to grant me ownership I can tinker with it a bit more and get some docs up

**Comment by palfvin** [comment]
I went ahead and created/pushed the project on relish in my account, so the link is at least working now. I'll leave it to @myronmarston to deal with any ownership issues.

**Comment by JonRowe** [comment]
TBH I'm happy with docs being published there :)

**Comment by yb66** [comment]
Thanks all, it's much appreciated. I opened the issue simply to improve the docs, I wasn't waiting, no apologies needed.

Kind regards,
iain

**Comment by myronmarston** [comment]
> If one of you wants to grant me ownership I can tinker with it a bit more and get some docs up

Done. (More for future use than anything).
